name: habita
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  calendar_date_picker2: ^0.5.5
  connectivity_plus: ^6.0.1
  country_flags: ^2.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  day_night_time_picker: ^1.3.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_heatmap_calendar: ^1.0.5
  flutter_localizations:
    sdk: flutter
  flutter_provider: ^2.1.0
  fluttericon: ^2.0.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  loading_animation_widget: ^1.2.1
  mockito: ^5.4.4
  pedometer: ^4.0.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  simple_circular_progress_bar: ^1.0.2
  supabase_flutter: ^2.3.4
  url_launcher: ^6.2.5
  uuid: ^4.4.0
  habits:
    git:
      url: https://github.com/MiksaMalaksa/habita_core.git

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/tg.png
    - assets/git_hub.png
    - assets/habita_logo.png
    - assets/dart.png
    - assets/busy.png
    - assets/streak.png

  fonts:
    - family: FontAwesome5
      fonts:
        - asset: fonts/awesome5.ttf

flutter_intl:
  enabled: true
