class SupabaseKeys{
  static const supaUrl = "https://pnokssgiafvaveptryiy.supabase.co";
  static const supaAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBub2tzc2dpYWZ2YXZlcHRyeWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTM4Nzg2MTMsImV4cCI6MjAyOTQ1NDYxM30.yJO2e4b3g9JzPTbRr7wXXH08GqYvvAFyJAA9N6GBbqQ";
}